version: "3.8"
services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    env_file:
      - mongodb.env
    volumes:
      - type: bind
        source: ./mongodb-data
        target: /data/db
